- name: generate SSH key
  hosts: 127.0.0.1
  connection: local
  vars:
    ssh_key_filename: id_rsa_myproject
  vars_prompt:
    - name: "ansible_user"
      prompt: "Digite o seu usuário da máquina"
      private: no
    - name: "ssh_passphrase"
      prompt: "Enter the passphrase for the SSH key"
      private: no
  tasks:
    - name: generate SSH key "{{ssh_key_filename}}"
      user:
        name: "{{ansible_user}}"
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: .ssh/{{ssh_key_filename}}
        ssh_key_passphrase: "{{ssh_passphrase}}"
        force: no